'use strict';
(function(){
function init(){
const fontStyles=document.querySelector('[data-fonts]');
if(fontStyles){const enable=()=>{fontStyles.media='all';};if(fontStyles.sheet)enable();else fontStyles.addEventListener('load',enable,{once:true});}
const lang=document.documentElement.lang;
const messages={fa:{empty:'مطلبی پیدا نشد.',error:'اطلاعات را بررسی کنید و دوباره تلاش کنید.',ready:'خلاصه آماده شد. برای ارسال، واتساپ را باز کنید.',open:'ارسال درخواست در واتساپ',copied:'خلاصه کپی شد.',offline:'ارسال مستقیم از طریق واتساپ آماده است.'},en:{empty:'No matching items.',error:'Check the details and try again.',ready:'Your brief is ready. Open WhatsApp to send it.',open:'Send request on WhatsApp',copied:'Brief copied.',offline:'Your direct WhatsApp message is ready.'},ar:{empty:'لم يتم العثور على نتيجة.',error:'راجع المعلومات وحاول مجدداً.',ready:'الملخص جاهز. افتح واتساب لإرساله.',open:'إرسال الطلب عبر واتساب',copied:'تم نسخ الملخص.',offline:'رسالة واتساب المباشرة جاهزة.'}}[lang];
const menu=document.querySelector('.menu');
const navigation=document.querySelector('.navlinks');
const closeMenu=()=>{navigation?.classList.remove('open');menu?.setAttribute('aria-expanded','false');};
menu?.addEventListener('click',()=>{navigation.classList.toggle('open');menu.setAttribute('aria-expanded',String(navigation.classList.contains('open')));});
const escapeMenu=e=>{if(e.key==='Escape'&&navigation?.classList.contains('open')){closeMenu();menu.focus();}};
menu?.addEventListener('keydown',escapeMenu);
navigation?.addEventListener('keydown',escapeMenu);
navigation?.addEventListener('click',e=>{if(e.target.closest('a'))closeMenu();});
const search=document.querySelector('[data-search]');
const category=document.querySelector('[data-category-filter]');
const normalize=s=>String(s).toLocaleLowerCase().normalize('NFKC').replace(/[يى]/g,'ی').replace(/ك/g,'ک').replace(/[أإآٱ]/g,'ا').replace(/[۰-۹]/g,d=>String(d.charCodeAt(0)-1776)).replace(/[٠-٩]/g,d=>String(d.charCodeAt(0)-1632)).replace(/[\u064b-\u065f\u0670\u0640\u200c-\u200f\u2066-\u2069]/g,'').replace(/\s+/g,' ').trim();
const searchable=Array.from(document.querySelectorAll('[data-searchable]'),element=>{const text=normalize(element.textContent+' '+(element.dataset.searchTerms||''));return {element,text,compact:text.replace(/\s/g,'')};});
const filter=()=>{let n=0;const query=normalize(search?.value||'');const terms=query.split(' ').filter(Boolean);const compact=query.replace(/\s/g,'');searchable.forEach(({element:e,text,compact:joined})=>{const textMatch=terms.every(t=>text.includes(t))||(compact&&joined.includes(compact));const match=Boolean(textMatch)&&(!category||category.value==='all'||e.dataset.category===category.value);e.hidden=!match;n+=match?1:0;});const count=document.querySelector('.searchcount');if(count)count.textContent=n?new Intl.NumberFormat(lang).format(n):messages.empty;};
search?.addEventListener('input',filter);category?.addEventListener('change',filter);
if(search||category)filter();
const doiTool=document.querySelector('[data-doi-tool]');
doiTool?.querySelector('form')?.addEventListener('submit',e=>{e.preventDefault();const input=doiTool.querySelector('input');if(!input.reportValidity())return;let value=input.value.trim().replace(/^doi:\s*/i,'').replace(/^https?:\/\/(?:dx\.)?doi\.org\//i,'');try{value=decodeURIComponent(value);}catch{value='';}const result=doiTool.querySelector('[data-doi-result]');result.replaceChildren();if(!/^10\.\d{4,9}\/\S+$/i.test(value)||/[\u0000-\u0020<>"\\]/.test(value)){result.textContent=doiTool.dataset.invalid;return;}const link='https://doi.org/'+encodeURIComponent(value).replace(/%2F/gi,'/');const p=document.createElement('p');p.textContent=doiTool.dataset.ready;const a=document.createElement('a');a.href=link;a.textContent=link;a.target='_blank';a.rel='noopener noreferrer';const b=document.createElement('button');b.type='button';b.className='btn ghost';b.textContent=doiTool.dataset.copy;b.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(link);b.textContent=doiTool.dataset.copied;}catch{p.textContent=doiTool.dataset.copyFailed;}});result.append(p,a,b);});
const form=document.querySelector('#consultation');form?.addEventListener('submit',async e=>{e.preventDefault();if(!form.reportValidity())return;const d=Object.fromEntries(new FormData(form));d.lang=lang;const status=form.querySelector('[role=status]');const b=form.querySelector('button[type=submit]');for(const key of ['name','contact','service','topic','degree','deadline'])d[key]=String(d[key]||'').trim().replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g,'');
if(d.name.length<2||d.name.length>100||d.contact.length<5||d.contact.length>150||d.topic.length<10||d.topic.length>2000||d.service.length>200||d.degree.length>100||d.website||d.consent!=='on'||(d.deadline&&(!/^\d{4}-\d{2}-\d{2}$/.test(d.deadline)||!Number.isFinite(Date.parse(d.deadline))||new Date(d.deadline).toISOString().slice(0,10)!==d.deadline))){status.textContent=messages.error;return;}
b.disabled=true;let result;const labels={fa:['درخواست مشاوره پژوهشی','نام','راه تماس','خدمت','مقطع','مهلت','موضوع'],en:['Research consultation','Name','Contact','Service','Degree','Deadline','Topic'],ar:['طلب استشارة بحثية','الاسم','التواصل','الخدمة','المرحلة','الموعد','الموضوع']}[lang];const brief=[labels[0],...[d.name,d.contact,d.service,d.degree,d.deadline,d.topic].map((v,i)=>labels[i+1]+': '+(v||'—'))].join('\n');try{if(location.protocol==='file:'||document.documentElement.hasAttribute('data-standalone'))throw Error('local');const r=await fetch('/api/consultation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)});result=await r.json();if(!r.ok)throw Error(result.error||'request');}catch(err){if(err.message==='local'||err instanceof TypeError){result={url:'https://wa.me/989124067596?text='+encodeURIComponent(brief)};}else{status.textContent=messages.error;b.disabled=false;return;}}
status.replaceChildren();const p=document.createElement('p');p.textContent=messages.ready;const a=document.createElement('a');a.href=result.url;a.className='btn';a.textContent=messages.open;a.target='_blank';a.rel='noopener noreferrer';status.append(p,a);b.disabled=false;});
const planner=document.querySelector('#planner');planner?.addEventListener('submit',e=>{e.preventDefault();if(!planner.reportValidity())return;const days=Number(new FormData(planner).get('days'));const names={fa:['تعریف مسئله و پروپوزال','مرور ادبیات و طراحی روش','گردآوری و آماده‌سازی داده','تحلیل و گزارش نتایج','بازبینی، ارجاع و آمادگی دفاع'],en:['Problem and proposal','Literature and methods','Data collection and preparation','Analysis and reporting','Revision, citations and defense'],ar:['المشكلة والمقترح','الأدبيات والمنهجية','جمع البيانات وإعدادها','التحليل والتقرير','المراجعة والمراجع والمناقشة']}[lang];let start=1;const weights=[.15,.2,.25,.25,.15];const ul=document.createElement('ol');names.forEach((name,i)=>{const len=i===4?days-start+1:Math.max(1,Math.floor(days*weights[i]));const li=document.createElement('li');li.textContent=name+' · '+start+'–'+(start+len-1);ul.append(li);start+=len;});const out=document.querySelector('#planresult');out.replaceChildren(ul);out.hidden=false;});

}
window.DidgarApp={init};
init();
})();
