import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import handler from '../api/consultation.mjs';
const files=[];const walk=d=>{for(const e of fs.readdirSync(d,{withFileTypes:true})){const p=path.join(d,e.name);if(e.isDirectory())walk(p);else if(p.endsWith('.html'))files.push(p);}};for(const l of ['fa','en','ar'])walk(l);
assert.equal(files.length,JSON.parse(fs.readFileSync('content/routes.json','utf8')).length);for(const p of files){const s=fs.readFileSync(p,'utf8');const lang=p.split(path.sep)[0];assert(s.includes(`lang="${lang}"`),p);assert.equal((s.match(/<h1\b/g)||[]).length,1,p);assert(s.includes('rel="canonical"'),p);for(const l of ['fa','en','ar','x-default'])assert(s.includes(`hreflang="${l}"`),p);for(const m of s.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g))JSON.parse(m[1]);const ids=[...s.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length,'Duplicate ID '+p);for(const m of s.matchAll(/(?:href|src)="(\/[^"#]*)(?:#[^"]*)?"/g)){const target=m[1];if(target.startsWith('/api/'))continue;const file=target.endsWith('/')?target.slice(1)+'index.html':target.slice(1);assert(fs.existsSync(file),'Broken local link '+p+' -> '+target);}}
async function call(method,body,headers={'content-type':'application/json'}){let status=200,result;const res={setHeader(){},status(n){status=n;return this;},json(d){result=d;return this;}};await handler({method,body,headers},res);return {status,result};}
const data={name:'Research Student',contact:'student@example.org',topic:'A study of research methods and data.',service:'Data analysis',degree:'Doctoral',deadline:'2026-12-01',lang:'en',consent:'on',website:''};let r=await call('POST',data);assert.equal(r.status,200);assert.equal(r.result.status,'ready_to_send');assert(r.result.url.startsWith('https://wa.me/989124067596?text='));assert(decodeURIComponent(r.result.url).includes(data.topic));assert.equal((await call('GET',data)).status,405);assert.equal((await call('POST',{...data,consent:''})).status,400);assert.equal((await call('POST',{...data,topic:'x'})).status,400);assert.equal((await call('POST',{...data,topic:'x'.repeat(2001)})).status,400);assert.equal((await call('POST',{...data,website:'spam'})).status,400);assert.equal((await call('POST',data,{'content-type':'text/plain'})).status,415);assert.equal((await call('POST','{bad')).status,400);for(const lang of ['fa','ar'])assert.equal((await call('POST',{...data,lang})).status,200);
console.log(`PASS: ${files.length} pages; internal links, unique IDs, language metadata, structured data and consultation API validation.`);

for(const invalid of [{name:'  '},{topic:'          '},{deadline:'2026-02-30'},{deadline:'2026-2-01'},{lang:'xx'},{contact:{}},{consent:true}]){
 assert.equal((await call('POST',{...data,...invalid})).status,400,JSON.stringify(invalid));
}
assert.equal((await call('POST',data,{'content-type':'application/json-injected'})).status,415);
assert.equal((await call('POST',data,{'content-type':'Application/JSON; charset=utf-8'})).status,200);
console.log('PASS: whitespace, impossible dates, invalid language/types, consent and JSON media type edge cases.');
