"""Authored prompts for editable foundation templates in three languages."""
PROMPTS = {
 'search-log': {
  'fa':['جمعیت، مفهوم و دامنه را به بلوک واژه تبدیل و محدودیت زبان/زمان را توجیه کنید.', 'نام پایگاه، رابط و فیلدهای جست‌وجو را ثبت کنید.', 'رشتۀ کامل با پرانتز، عملگر و تاریخ قطع را حفظ و در همان رابط آزمون کنید.', 'تعداد واقعی قبل/بعد از محدودیت و دلیل آن را ثبت کنید.', 'فایل، قالب و روش حذف تکراری را ثبت و رکورد/گزارش/مطالعه را جدا کنید.'],
  'en':['Translate population, concepts and scope into blocks and justify date/language limits.', 'Record database, interface and searched fields.', 'Save the full query, operators, parentheses and cutoff; test it in the actual interface.', 'Record actual counts before/after limits and their rationale.', 'Log filename, format and deduplication; distinguish record, report and study.'],
  'ar':['حول المجتمع والمفهوم لكتل وبرر الوقت واللغة.', 'سجل القاعدة والواجهة والحقول.', 'احفظ الاستعلام والمعاملات والقطع واختبره في الواجهة.', 'سجل الأعداد الفعلية قبل القيود وبعدها وسببها.', 'وثق الملف وإزالة التكرار وميز السجل والتقرير والدراسة.']},
 'data-management-plan': {
  'fa':['منشأ، نوع فایل، مقدار مورد انتظار و مجوز تولید/گردآوری را بنویسید.', 'فرهنگ، README، نسخه و مسئول مستندسازی را مشخص کنید.', 'هویت و داده پژوهش را جدا و مجوز انتقال و خطر بازشناسایی را بررسی کنید.', 'مسئول، محل مجاز پشتیبان و آزمون بازیابی را تعیین کنید؛ اطلاعات حساس را اینجا نگذارید.', 'مدت حفظ را از رضایت/قرارداد/سیاست تعیین و مخزن، مجوز یا دسترسی مقید را توضیح دهید.'],
  'en':['Document provenance, file types, volume and collection permissions.', 'Specify dictionary, README, versions and documentation responsibility.', 'Separate identity and research files; assess transfer rights and identification risk.', 'Assign permitted backups and restoration tests; do not insert sensitive data here.', 'Derive retention from consent/agreements/policy; specify repository, licence or controlled access.'],
  'ar':['وثق المنشأ والنوع والحجم والإذن.', 'حدد القاموس وREADME والنسخ والمسؤول.', 'افصل الهوية والبحث وافحص النقل وخطر التعرف.', 'حدد النسخ واختبار الاستعادة ولا تدخل معلومات حساسة.', 'حدد الحفظ من الموافقة والعقد والسياسة والمستودع والترخيص أو الوصول المقيد.']},
 'data-dictionary': {
  'fa':['نام دقیق ستون و نسخۀ فایل را ثبت کنید؛ نام هم‌معنا را بدون دلیل ادغام نکنید.', 'سازه، ابزار، زمان و وضعیت خام/مشتق را بنویسید.', 'نوع، واحد و قرارداد تاریخ، اعشار و طبقه را مشخص کنید.', 'دامنۀ واقعی و معنای کدها را بنویسید؛ بازۀ آموزشی را به دادۀ نامرتبط تحمیل نکنید.', 'کد فقدان، منشأ، تبدیل و حق استفاده را شرح دهید؛ −۹۹ ممکن است کد باشد.'],
  'en':['Record exact column names and file version; justify merged labels.', 'Record construct, instrument, timing and raw/derived status.', 'Define type, units and date/decimal/category conventions.', 'Specify actual ranges and code meanings; do not impose the example range on unrelated data.', 'Explain missing codes, provenance, transformations and rights; −99 may be a code.'],
  'ar':['سجل اسم العمود والنسخة وبرر الدمج.', 'حدد البناء والأداة والوقت والخام أو المشتق.', 'حدد النوع والوحدة والتاريخ والعشرية والفئة.', 'حدد النطاق ومعاني الرموز ولا تفرض نطاق المثال.', 'اشرح الفقد والمنشأ والتحويل والإذن؛ قد يكون −٩٩ رمزاً.']},
 'preregistration-plan': {
  'fa':['سؤال، هدف برآورد و فرض مرتبط را بنویسید و شناخت قبلی داده را اظهار کنید.', 'پیامد اصلی، واحد، زمان، جامعه، انتخاب و ورود را عملیاتی کنید.', 'ورودی توان/دقت، ریزش و توقف را پیش از نتیجه توجیه کنید.', 'قواعد حذف، فقدان و outlier را با فرض روش مشخص کنید.', 'مدل، تعدیل، چندگانگی، حساسیت و مرز استکشاف را ثبت کنید.', 'تغییر را با تاریخ، اطلاعات دیده‌شده، دلیل و اثر ثبت کنید؛ برنامۀ قبلی را بی‌صدا عوض نکنید.'],
  'en':['State question, estimand and relevant hypotheses; disclose prior data knowledge.', 'Operationalize primary outcome, units, timing, population, sampling and eligibility.', 'Justify power/precision inputs, attrition and stopping before results.', 'Specify exclusion, missingness and outlier rules with assumptions.', 'Record model, adjustment, multiplicity, sensitivity and exploratory boundaries.', 'Date changes, data already seen, reasons and consequences; preserve the old plan.'],
  'ar':['حدد السؤال والهدف والفرض وصرح بمعرفة البيانات.', 'شغل النتيجة والوحدة والوقت والمجتمع والمعاينة والأهلية.', 'برر القوة أو الدقة والفقد والتوقف مسبقاً.', 'حدد الاستبعاد والفقد والشاذ وفروض الطريقة.', 'وثق النموذج والضبط والتعدد والحساسية والاستكشاف.', 'أرخ التغير والاطلاع والسبب والأثر واحفظ الخطة القديمة.']},
 'reviewer-response': {
  'fa':['نظر و شمارۀ داور را با رعایت محرمانگی حفظ کنید.', 'برداشت نقد، پاسخ علمی و شاهد را روشن و محترمانه شرح دهید.', 'اقدام انجام‌شده یا دلیل علمی عدم اجرا و جایگزین را بنویسید.', 'بخش، صفحه، جدول/خط و نسخۀ اصلاح‌شده را مشخص و تغییر واقعی را بررسی کنید.', 'نویسندگان اعداد و اظهارها را کنترل و سیاست AI محل را بخوانند.'],
  'en':['Retain comments and reviewer numbers with appropriate confidentiality.', 'Explain interpretation, scientific response and evidence respectfully.', 'Describe implemented actions or a reasoned limitation and alternative.', 'Identify section/page/table/line and revised version; verify the actual change.', 'Authors check numbers and claims and review the outlet’s AI policy.'],
  'ar':['احفظ التعليق ورقمه والسرية.', 'وضح الفهم والرد والدليل باحترام.', 'صف الإجراء أو سبب عدمه والبديل.', 'حدد الموضع والنسخة وتأكد من التغيير.', 'يراجع المؤلفون الأعداد والدعاوى وسياسة AI.']},
 'research-readme': {
  'fa':['هدف، نسخه و واقعی یا ساختگی بودن داده را صریح بنویسید.', 'منشأ، رضایت و مجوز داده و کد را جدا ثبت کنید.', 'نسخۀ واقعی سیستم و Python/بسته‌ها و نیاز اختیاری Quarto را مشخص کنید.', 'دستورها را از مسیر پروژه به ترتیب با ورودی/خروجی بنویسید؛ مسیر خصوصی را حذف کنید.', 'فایل انتظاررفته، آزمون با جواب معلوم و معیار شکست را شرح دهید؛ خروجی قدیمی بازاجرا نیست.', 'فرض‌ها، قابلیت انتقال محیط، محدودیت علمی و مسئول نگهداری را بنویسید.'],
  'en':['State purpose, version and whether the data are real or synthetic.', 'Separate provenance, consent and data/code licences.', 'Record actual system/Python/package versions and optional Quarto requirements.', 'List ordered commands from the project folder with inputs/outputs; remove private paths.', 'Document expected files, known-answer checks and failure criteria; old output is not replay.', 'Explain assumptions, environment portability, scientific limits and maintenance.'],
  'ar':['حدد الغرض والنسخة وحقيقة البيانات أو اصطناعيتها.', 'افصل المنشأ والموافقة وترخيص البيانات والكود.', 'سجل النظام والنسخ ومتطلبات Quarto الاختيارية.', 'اكتب الأوامر المرتبة ومدخلاتها ومخرجاتها بلا مسار خاص.', 'اشرح المتوقع واختبارات الجواب والفشل؛ القديم ليس إعادة تنفيذ.', 'وضح الفروض والنقل والحدود والصيانة.']}
}

def template_prompts(lang,filename):
    return PROMPTS[filename][lang]
